//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 11:59:42 AM CST 
//


package bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderDetail",
    "requestcommonfpkj"
})
@XmlRootElement(name = "business")
public class Business {

    @XmlElement(name = "CUSTOMDATA", required = true)
    protected OrderDetail orderDetail;
    @XmlElement(name = "REQUEST_COMMON_FPKJ", required = true)
    protected RequestCommonFpkj requestcommonfpkj;
    @XmlAttribute(name = "id")
    protected String id;

    
    public OrderDetail getOrderDetail() {
	
		return orderDetail;
	}


	public void setOrderDetail(OrderDetail orderDetail) {
	
		this.orderDetail = orderDetail;
	}


	public RequestCommonFpkj getRequestcommonfpkj() {
	
		return requestcommonfpkj;
	}


	public void setRequestcommonfpkj(RequestCommonFpkj requestcommonfpkj) {
	
		this.requestcommonfpkj = requestcommonfpkj;
	}


	public RequestCommonFpkj getREQUESTCOMMONFPKJ() {
        return requestcommonfpkj;
    }

   
    public void setREQUESTCOMMONFPKJ(RequestCommonFpkj value) {
        this.requestcommonfpkj = value;
    }

 
    public String getId() {
        return id;
    }

   
    public void setId(String value) {
        this.id = value;
    }

}
